# Generated by Django 2.2.3 on 2019-08-22 22:45

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.PositiveSmallIntegerField(choices=[(1, 'Doctor'), (2, 'Lab People'), (3, 'Receptionist'), (4, 'Patient'), (5, 'Administration')], null=True)),
                ('sex', models.BooleanField(blank=True, null=True)),
                ('tel_no', models.CharField(blank=True, max_length=255, null=True)),
                ('dob', models.DateField(blank=True, db_column='DOB', null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Disease',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Hospital',
            },
        ),
        migrations.CreateModel(
            name='MedicalSupply',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('stock', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Medical supply',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('checked_in', models.BooleanField(default=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('waiting_time', models.TimeField(blank=True, db_column='waiting time', null=True)),
                ('doctorid', models.ForeignKey(blank=True, db_column='doctorID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sche_doc', to=settings.AUTH_USER_MODEL)),
                ('patient', models.OneToOneField(db_column='patient', on_delete=django.db.models.deletion.CASCADE, related_name='sche_pat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Schedule',
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('report', models.FileField(blank=True, upload_to='lab_report')),
                ('conductor', models.ForeignKey(db_column='conductor', on_delete=django.db.models.deletion.DO_NOTHING, related_name='conduct', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(db_column='doctor', on_delete=django.db.models.deletion.CASCADE, related_name='doc', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(db_column='patient', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Lab test',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('tel_no', models.CharField(max_length=255)),
                ('hospital', models.ForeignKey(blank=True, db_column='hospital', null=True, on_delete=django.db.models.deletion.CASCADE, to='health.Hospital')),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Phr',
            fields=[
                ('patient', models.OneToOneField(db_column='patient', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='phr_pat', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=65535, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=65535, null=True)),
                ('disease', models.ForeignKey(db_column='disease', on_delete=django.db.models.deletion.CASCADE, to='health.Disease')),
                ('doctorid', models.ForeignKey(blank=True, db_column='doctorID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phr_doc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PHR',
            },
        ),
        migrations.CreateModel(
            name='Orderdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('medicalsupply', models.ForeignKey(db_column='medicalSupply', on_delete=django.db.models.deletion.CASCADE, to='health.MedicalSupply')),
                ('orderid', models.ForeignKey(db_column='orderID', on_delete=django.db.models.deletion.CASCADE, to='health.Order')),
            ],
            options={
                'db_table': 'OrderDetail',
                'unique_together': {('orderid', 'medicalsupply')},
            },
        ),
        migrations.CreateModel(
            name='Ehr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('medicalsupply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.MedicalSupply')),
                ('schedule', models.ForeignKey(db_column='schedule', on_delete=django.db.models.deletion.CASCADE, to='health.Schedule')),
            ],
            options={
                'db_table': 'EHR',
                'unique_together': {('schedule', 'medicalsupply')},
            },
        ),
    ]
