# Generated by Django 2.2.3 on 2019-07-18 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('tel_no', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Disease',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Hospital',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('report', models.TextField()),
            ],
            options={
                'db_table': 'Lab test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalSupply',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('stock', models.IntegerField()),
            ],
            options={
                'db_table': 'Medical supply',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'Order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField(db_column='DOB')),
                ('sex', models.BooleanField(blank=True, null=True)),
                ('tel_no', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('nin', models.IntegerField(db_column='NIN', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Patient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('date_time', models.DateTimeField(db_column='date&time')),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('waiting_time', models.TimeField(db_column='waiting time')),
            ],
            options={
                'db_table': 'Schedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('tel_no', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Staff',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ehr',
            fields=[
                ('schedule', models.ForeignKey(db_column='schedule', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='health.Schedule')),
                ('amount', models.IntegerField()),
            ],
            options={
                'db_table': 'EHR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orderdetail',
            fields=[
                ('orderid', models.ForeignKey(db_column='orderID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='health.Order')),
                ('amount', models.IntegerField()),
            ],
            options={
                'db_table': 'OrderDetail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Phr',
            fields=[
                ('patient', models.ForeignKey(db_column='patient', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='health.Patient')),
                ('weight', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'PHR',
                'managed': False,
            },
        ),
    ]
