# Generated by Django 2.2.3 on 2019-08-23 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ehr',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ehr',
            name='medicalsupply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health.MedicalSupply'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='conductor',
            field=models.ForeignKey(blank=True, db_column='conductor', on_delete=django.db.models.deletion.DO_NOTHING, related_name='conduct', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='notes',
            field=models.CharField(blank=True, max_length=65535, null=True),
        ),
    ]
