# Generated by Django 2.2.3 on 2019-08-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_labtest_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='lab_report'),
        ),
    ]
