# Generated by Django 2.2.3 on 2019-08-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_auto_20190824_0834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='notes',
            new_name='prescriptions',
        ),
        migrations.AddField(
            model_name='schedule',
            name='sysmptoms',
            field=models.TextField(blank=True, max_length=65535, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='treatment',
            field=models.TextField(blank=True, max_length=65535, null=True),
        ),
    ]
