# Generated by Django 2.2.3 on 2019-08-25 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0008_schedule_diagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='patient',
            field=models.ForeignKey(db_column='patient', on_delete=django.db.models.deletion.CASCADE, related_name='sche_pat', to=settings.AUTH_USER_MODEL),
        ),
    ]
