# Generated by Django 2.2.3 on 2019-08-25 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0009_auto_20190825_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
