# Generated by Django 2.2.3 on 2019-08-25 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0010_schedule_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='patient',
            field=models.ForeignKey(blank=True, db_column='patient', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sche_pat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
