# Generated by Django 2.2.3 on 2019-08-26 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0012_auto_20190825_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
